# Generated by Django 4.1.7 on 2026-01-19 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('code', models.CharField(help_text='IATA airport code (3 characters)', max_length=3, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='Full name of the airport', max_length=100)),
                ('position', models.IntegerField(help_text='Position in the route sequence (used for left/right traversal)')),
            ],
            options={
                'verbose_name': 'Airport',
                'verbose_name_plural': 'Airports',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(help_text='Flight duration in minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the route was created')),
                ('destination', models.ForeignKey(help_text='Destination airport for this route', on_delete=django.db.models.deletion.CASCADE, related_name='incoming_routes', to='routes.airport')),
                ('source', models.ForeignKey(help_text='Source airport for this route', on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_routes', to='routes.airport')),
            ],
            options={
                'verbose_name': 'Route',
                'verbose_name_plural': 'Routes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='airport',
            index=models.Index(fields=['position'], name='routes_airp_positio_9bd3fa_idx'),
        ),
        migrations.AddIndex(
            model_name='airport',
            index=models.Index(fields=['code'], name='routes_airp_code_0aae2b_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['source', 'destination'], name='routes_rout_source__0c7100_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['duration'], name='routes_rout_duratio_4d4ed3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together={('source', 'destination')},
        ),
    ]
