# Generated by Django 4.1.7 on 2026-01-19 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='position',
            field=models.IntegerField(help_text='Position in the route sequence (used for left/right traversal)', unique=True),
        ),
    ]
