# Generated by Django 4.1.7 on 2026-01-19 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_rename_duration_to_distance'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['distance'], name='routes_rout_distanc_77243c_idx'),
        ),
    ]
