# Generated by Django 4.1.7 on 2026-01-19 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_remove_route_routes_rout_distanc_4d4ed3_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='route',
            name='routes_rout_duratio_4d4ed3_idx',
        ),
    ]
